---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cms-trigger-release-mock
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Deployment
    tekton.dev/tags: deploy
    tekton.dev/displayName: "argocd"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task is a mock trigger for our change management system. It triggers an ArgoCD release based on a git ref.

  params:
    - name: revision
      description: The revision to sync to
      default: HEAD
      type: string
    - name: git-repo
      description:  Repository URL
      default: https://github.com/lijcam/heroes-argo-release.git
      type: string 
    - name: app-name
      type: string
      default: heroes
    - name: path
      description: Path in app definition
      default: ./App/
    - name: environment
      type: string
      default: dev-test
    - name: argocd-version
      default: "1.9"
      type: string
  stepTemplate:
    envFrom:
      - configMapRef:
          name: argocd-env-configmap
      - secretRef:
          name: argocd-env-secret
  steps:
    - name: wait-for-release
      image: registry.redhat.io/openshift-gitops-1/argocd-rhel8:$(params.argocd-version)
      script: |
        #!/usr/bin/env bash
        set -x
        yes | argocd login "$ARGOCD_SERVER" --username="$ARGOCD_USERNAME" --password="$ARGOCD_PASSWORD";

        argocd app create "$(params.app-name)" --repo $(params.git-repo) --path $(params.path) --dest-namespace $(params.environment)-$(params.app-name) --label cms.release=$(params.app-name) --dest-server https://kubernetes.default.svc --sync-option CreateNamespace=true 
        argocd app sync -l cms.release=$(params.app-name)

        argocd app wait -l cms.release=$(params.app-name) --health

        argocd logout "$ARGOCD_SERVER"